site_name: みそ日記

theme:
  name: mkdocs
  locale: zh_CN
  custom_dir: overrides

nav:
  - 首页: index.md
  - 有的没的: books/index.md
  - 没的有的: films/index.md
  - 有的有的: notes/index.md
  - 没的没的: mengyao/index.md

extra_css:
  - style.css

markdown_extensions:
  - attr_list

hooks:
  - hooks/passwords.py

plugins:
  - search
  - encryptcontent:
      title_prefix: ''
      summary: '回答一个问题，翻开这一页。'
      placeholder: '请输入你的答案'
      password_button: true
      password_button_text: '翻开'
      decryption_failure_message: '还没对上暗号，再想想？'
      encryption_info_message: ''

      remember_keys: true
      remember_password: false
      remember_prefix: 'miso_diary_'
      search_index: 'encrypted'
      threshold_warning_min_entropy: 0
